name: HouseKeep

on:
  schedule:
    - cron: '0 0 * * 6'
  push:
jobs:
  dotnet:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-dotnet@v1.4.0
    - run: |
        dotnet tool restore
        dotnet nukeeper repo https://github.com/Freeesia/vivideo ${{ secrets.GitHubToken }}
